version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  database:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports: []  # Don't expose database port in production

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports: []  # Don't expose redis port in production

  api:
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      MASTER_ENCRYPTION_KEY: ${MASTER_ENCRYPTION_KEY}
      REDIS_URL: redis://:${REDIS_PASSWORD:-}@redis:6379

  web:
    environment:
      NODE_ENV: production

  # Production Nginx with SSL
  nginx:
    image: nginx:alpine
    container_name: configmaster-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - api
    networks:
      - config-management-network
    restart: unless-stopped

volumes:
  postgres_data_prod:
    driver: local